Update currentJob

diff --git a/cloud/aws/currentJob b/cloud/aws/currentJob
--- a/cloud/aws/currentJob
+++ b/cloud/aws/currentJob
@@ -1,52 +1,53 @@
-  1 #!/bin/bash
-  2 #Author: Raymo "papiFresco" Gumti
-  3 #Version: 1.3
-  4 set -eu 
-  5 
-  6 if ! [ -f /usr/bin/aws ]; then
-  7         logger -t $(basename $0) "/usr/bin/aws not found. exit 1"
-  8         exit 1
-  9 fi
- 10 
- 11 PAGE_RESULT=$(curl -s  < FARM URL > | grep HREF | awk -F \> /$(hostname)/'{gsub("</TD","");print $4}')
- 12 if [ "$PAGE_RESULT" = "Take Out" ]; then
- 13         FARM_STATUS=IN
- 14 elif [ "$PAGE_RESULT" = "Put In" ]; then
- 15         FARM_STATUS=OUT
- 16 else    
- 17         logger -t $(basename $0) "< FARM URL > UNREACHABLE"
- 18         exit 1
- 19 fi
- 20 
- 21 
- 22 
- 23 RUNNING_JOB=$(sudo -u $FARM_USER grep PROJECT /tmp/farm2.log | tail -1| cut -d "." -f11- | cut -d '/' -f4)
- 24 
- 25 JOB_STATUS=$(sudo -u $FARM_USER grep COMPLETED /tmp/farm2.log | cut -d ' ' -f2)
- 26 
- 27 #query farm & job status to see whats popping?
- 28 if [ "$FARM_STATUS" = "OUT" ] || [ "$JOB_STATUS" = "COMPLETED" ]; then
- 29 
- 30         echo "NONE"  > /tmp/currentJob.txt
- 31 
- 32 else
- 33 
- 34         echo "$RUNNING_JOB" > /tmp/currentJob.txt
- 35 
- 36 fi
- 37 CURRENT_JOB=$(cat /tmp/currentJob.txt)
- 38 
- 39 #check if current job changes, if so set the tags. If it aint doing shit, then dont do shit.
- 40 if [ "$RUNNING_JOB" == "$CURRENT_JOB" ]; then
- 41         
- 42         INSTANCE_ID=$(GET http://169.254.169.254/latest/meta-data/instance-id)
- 43         VOLUME_ID=$(aws ec2 describe-volumes --filters Name=attachment.instance-id,Values="$INSTANCE_ID" --query 'Volumes[*].{ID:VolumeId}' --output text)
- 44         SET_JOB_TAGS=$(aws ec2 create-tags --resources "$INSTANCE_ID" "$VOLUME_ID" --tags Key=Job,Value="$CURRENT_JOB")
- 45 
- 46         $SET_JOB_TAGS
- 47 
- 48 else
- 49 
- 50         echo 0 > /dev/null
- 51 
- 52 fi
+#!/bin/bash
+#Author: Raymo "papiFresco" Gumti
+#Version: 1.3
+set -eu 
+
+if ! [ -f /usr/bin/aws ]; then
+        logger -t $(basename $0) "/usr/bin/aws not found. exit 1"
+        exit 1
+fi
+
+PAGE_RESULT=$(curl -s  http://FARMURL/status/farm | grep HREF | awk -F \> /$(hostname)/'{gsub("</TD","");print $4}')
+if [ "$PAGE_RESULT" = "Take Out" ]; then
+        FARM_STATUS=IN
+elif [ "$PAGE_RESULT" = "Put In" ]; then
+        FARM_STATUS=OUT
+else
+        logger -t $(basename $0) "http://FARM-URL.com:50555/status/farm UNREACHABLE"
+        exit 1
+fi
+
+
+
+RUNNING_JOB=$(sudo -u $FARM_USER grep PROJECT /tmp/farm2.log | tail -1| cut -d "." -f11- | cut -d '/' -f4)
+
+JOB_STATUS=$(sudo -u $FARM_USER grep COMPLETED /tmp/farm2.log | cut -d ' ' -f2)
+
+#query farm & job status to see whats popping?
+if [ "$FARM_STATUS" = "OUT" ] || [ "$JOB_STATUS" = "COMPLETED" ]; then
+
+        echo "NONE"  > /tmp/currentJob.txt
+        logger -t $(basename $0) "currentJob script will not update instance tags :Running Job = `cat /tmp/currentJob.txt`"
+
+else
+
+        echo "$RUNNING_JOB" > /tmp/currentJob.txt
+
+fi
+CURRENT_JOB=$(cat /tmp/currentJob.txt)
+
+#check if current job changes, if so set the tags. If it aint doing shit, then dont do shit.
+if [ "$RUNNING_JOB" == "$CURRENT_JOB" ]; then
+
+        INSTANCE_ID=$(GET http://169.254.169.254/latest/meta-data/instance-id)
+        VOLUME_ID=$(aws ec2 describe-volumes --filters Name=attachment.instance-id,Values="$INSTANCE_ID" --query 'Volumes[*].{ID:VolumeId}' --output text)
+        SET_JOB_TAGS=$(aws ec2 create-tags --resources "$INSTANCE_ID" "$VOLUME_ID" --tags Key=Job,Value="$CURRENT_JOB")
+
+        $SET_JOB_TAGS
+        logger -t $(basename $0) "Current render job is $RUNNING_JOB"
+else
+
+        echo 0 > /dev/null
+        logger -t $(basename $0) "currentJob script will not instance tags :Running Job = $RUNNING_JOB"
+fi
